language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

install:
  - composer self-update
  - composer install --dev

services: mongodb

before_script: echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: make test

after_script: php vendor/bin/coveralls

notifications:
  email:
    - igor.timoshenko@i.ua
